# Site settings
title:              Guanghe
email:              dev@guanghe.tv
description:        "光合新知开发者博客"
baseurl:            /
url:                "http://dev.guanghe.tv"
twitter_username:   guanghetv
github:
  repo:             https://github.com/guanghetv
  bookshelf:        https://github.com/guanghetv/books/wiki
lagou:              http://www.lagou.com/gongsi/5706.html
paginate:           5


# Build settings
markdown:           redcarpet
permalink:          /:year/:month/:title.html
highlighter:        pygments  